# Generated by Django 5.0.1 on 2024-01-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='masoud', max_length=200),
            preserve_default=False,
        ),
    ]
